### ISSUE TITLE
Change ConfigurationParser to parse YAML instead of TOML

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-agent#103]
**Parent Issue:** https://github.com/wazuh/wazuh-agent/issues/241

## Description

The current implementation of the `ConfigurationParser` can parse TOML files, but after some consideration we need to change this and make the parser able to interpret YAML files, as that will be the configuration format across all Wazuh components.

Tasks to be accomplished:

- [x] Select and use a common and maintained library, mention the advantages and disadvantages of its use.
- [x] Replace the TOML library with the selected YAML library.
- [x] Rename the default configuration file to _wazuh-agent.yml_, which must be installed into _/etc/wazuh-agent/wazuh-agent.yml_.
- [x] Adapt and create new UT for the 'ConfigurationParser'.

**Comment by Nicogp** [comment]
## Research of yaml libraries available for C++

The official [YAML page](https://yaml.org/) lists the following libraries:

> YAML Frameworks and Tools:
>   C/C++:
>   - [libfyaml](https://github.com/pantoniou/libfyaml)      # "C" YAML 1.2 processor ([YTS](https://yaml.org/#yts))
>   - [libyaml](http://pyyaml.org/wiki/LibYAML)       # "C" Fast YAML 1.1 ([YTS](https://yaml.org/#yts))
>   - [libcyaml](https://github.com/tlsa/libcyaml)      # YAML de/serialization of C data (using libyaml)
>   - [yaml-cpp](https://github.com/jbeder/yaml-cpp/)      # C++ YAML 1.2 implementation
the only one native for C++ is yaml-cpp, the rest are native for C.

If we take [cppreference ](https://en.cppreference.com/w/cpp/links/libs)as a source, here it names only yaml-cpp:
![image](https://github.com/user-attachments/assets/fe6b0fd1-32ea-4acd-8a68-5f08ecbdde4b)

### Comparison of libraries: 
While researching, we also found the rapidyaml library that was included for comparison.

**YAML-CPP:**
https://github.com/jbeder/yaml-cpp

- Advantages:

  - Supports recent YAML versions. Full support for YAML specification
  - Open source, widely used and supported
  - Easy to install (available in vcpkg).
  - Provides intuitive data access for hierarchical structures.
  - Integrates smoothly into projects using CMake.

- Disadvantages:

  - Can be heavy for small projects or those with strict performance requirements.

**libyaml:**
https://pyyaml.org/wiki/LibYAML

- Advantages:

  - Lightweight and fast.
  - Suitable for projects needing high performance and simple data access.

- Disadvantages:

  - Less intuitive interface compared to YAML-CPP.
  - More complex API
  - Requires more manual parsing code
  - Less user-friendly for direct use
  - Limited support for advanced YAML features, potentially lacking full YAML specification support.

**RapidYAML:**
https://github.com/biojppm/rapidyaml

- Advantages:

  - Excellent performance, ideal for large YAML files.
  - Modern, efficient API.

- Disadvantages:

  - Relatively young project, so it might lack advanced features or community support compared to YAML-CPP.
  - Fewer features than other libraries
  - Limited support for complex YAML structures.
  - Less intuitive syntax

**libfyaml:**
https://github.com/pantoniou/libfyaml

- Advantages:

  - Provides full YAML 1.2 compliance, including advanced YAML features.
  - Very fast and optimized for performance, with a focus on low-level flexibility.
  - Highly modular design, making it adaptable for many types of applications.

- Disadvantages:

  - Primarily a C library, so using it with C++ may require some wrappers or adaptations for optimal integration.
  - Still a relatively new library, so it might have less documentation and community support compared to more mature libraries.


**libcyaml:**
https://github.com/tlsa/libcyaml

- Advantages:

  - Type-safe parsing due to schema definitions, which reduces runtime errors.
  - Lightweight and performs well due to its schema-based approach.
  - Well-suited for projects needing strict type control and reliable error handling.

- Disadvantages:

  - Limited YAML feature support; works best with simple, well-defined YAML structures.
  - Schemas may be restrictive for more flexible YAML formats and can add setup complexity.


## Conclusion
With the analysis of all the libraries, I choose for the moment to use yaml-cpp, because it is native to C++, fully supports the YAML specifications, is OpenSource and is widely used and maintained.

**Comment by Nicogp** [comment]
(2024/11/01)

- I started to make the changes
- I changed the toml11 library to yaml-cpp
- I changed in the configurationParser module to use the new library
