### ISSUE TITLE
Develop Launch Daemon for macOS

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#132]
**Parent Issue:**
- https://github.com/wazuh/wazuh-agent/issues/127

## Description

This subtask is focused on developing a launch daemon for macOS to manage the Wazuh agent as a background service. The daemon must ensure the agent starts at boot and supports basic service control options.

## Functional Requirements

- Create a `launchd` configuration for managing the Wazuh agent.
- Implement functionality for starting, stopping, and restarting the agent.

## Non-Functional Requirements

- Ensure compatibility with macOS 14+.

## Acceptance Criteria

- The Wazuh agent is managed via a launch daemon that starts the agent on system boot.
- Administrators can use `launchctl` to manage the service (start, stop, restart).

**Comment by aritosteles** [comment]
# Update

- **2024/10/15**:
Doing research about launchd. Attempting to set up a local macOs Sonoma vm.

**Comment by aritosteles** [comment]
# Conclusions

Launchd is a bit different from systemd but those differences are subtle enough to go unnoticed while still crashing the agent.

Key points to be taken into consideration:

- We need to set the command line argument as a separate string in the service file. Otherwise launch looks for ```/path/wazuh-agent --start``` and does not find the executable. So the ```--start``` gets its own ```<string>```. 

- We need to set the working directory in the service file. Otherwise the agent fails to create the SQLite databases.

- Launchd does not capture or redirect output unless specified in the service file. So we have ```<key>StandardOutPath</key>``` and ```<key>StandardErrorPath</key>``` to set.

## Some tips

- After a crash (or a few) the application gets put in the "penalty box" and will not run. To get it out of the penalty box use:
```sudo launchctl bootout system /Library/LaunchDaemons/com.wazuh.agent.plist```

- ```launchctl load``` seems to have been replaced by ```launchctl bootstrap``` so to load the agent use:
```sudo launchctl bootstrap system /Library/LaunchDaemons/com.wazuh.agent.plist```

- To get a status after running ```launchctl bootstrap``` use:
```sudo launchctl print system/com.wazuh.agent```.
