### ISSUE TITLE
Agent does not reconnect after service restoration if both DNS and Wazuh fail

### ISSUE THREAD

**Issue by mmccarn** [wazuh/wazuh-agent#216]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-1 | wazuh-agent | Agent | Packages | macOS 14.6.1 |
| 4.9.0-1 | wazuh-agent | Agent | Packages | macOS 15.0.1 |
| 4.9.0-1 | wazuh-agent | Agent | Packages | Ubuntu 22.04.5 LTS |
| 4.9.0-1 | wazuh-agent | Agent | Packages | Debian GNU/Linux 12 |
| 4.9.0-1 | wazuh-agent | Agent | Packages | Centos 7 |
| 4.9.0-1 | wazuh-agent | Agent | Packages | Microsoft Windows 10 Pro 10.0.19045.5011 |

## Relevant Configuration Details

* All-in-one Wazuh server (proxmox guest)
* Local DNS (proxmox guest, same node as Wazuh server)
* Agents configured to connect to Wazuh using DNS hostname

## Incident Details

* proxmox node failed
* proxmox node rebooted
* wazuh operation restored
* physical agents, and agents from other nodes, did not reconnect
* agents remained disconnected for over 24 hours
* agents reconnected successfully using `.../bin/wazuh-control restart`

## Questions

* Should disconnected agents reset themselves periodically?
  * Is there a configuration option to enable this behavior, or a scheduled task I can create?
* If this is something that deserves developer time, are there logs I should provide?

[edit - add Windows guest and correct spelling]

**Comment by vikman90** [comment]
Hi @mmccarn,

Wazuh agents are designed to periodically retry connections to the Wazuh Manager, even after a disconnection. This includes re-resolving DNS hostnames at every connection attempt. In versions prior to 3.12, the agent suffered from limitations where DNS resolution occurred only at startup due to restrictions related to chroot environments. However, starting with version 4.0, this behavior was improved with the introduction of auto-enrollment and DNS resolution at every connection retry.

Given that your agents remained disconnected for over 24 hours and only reconnected after a manual restart, this suggests that there might be an issue in how the agents are integrated with your Proxmox setup, as it involves both DNS and Wazuh services running on the same node.

We conducted a test by modifying the Wazuh Manager IP address in /etc/hosts while the agents were attempting to reconnect. The agents correctly resolved the nameserver and reconnected each time the IP was changed. This indicates that DNS resolution is functioning properly within the agent during reconnection attempts.

If you wish to enforce stricter reconnection policies, you can configure a scheduled task (cron job) on your agents to periodically restart the agent service if it is found to be disconnected. This is more of a workaround, but it may help maintain agent connectivity during such scenarios.

To assist in a more detailed analysis, could you describe your Proxmox configuration in more detail? Specifically:

- How many guests are running on your setup?
- Are there any networking or DNS resolution issues that could potentially affect communication between the agents and the Wazuh Manager?

**Comment by mmccarn** [comment]
Thanks.

&nbsp;

Documenting this makes me realize I need to simplify my DNS configuration; I'll work on that and post back here if I think there is still a problem related to the wazuh agent.

&nbsp;

* DHCP serves the router for DNS
* The router uses DNS_A (pi-hole on Host 1)
* some systems with hard-coded IPs use DNS_B on Host 2 for DNS, which uses DNS_0 on the router
  (DNS lookups sent to DNS_B go from there to DNS_0, then to DNS_A, then off-site...)


* Sophos Firewall (DNS_0)
* Host 1 (5 active guests)
  * Wazuh
  * pi-hole (DNS_A)
  * ubuntu
  * ubuntu
  * centos
* Host 2 (3 active guests)
  * windows
  * centos (DNS_B)
  * ubuntu
* Host 3 (4 active guests)
  * ubuntu
  * ubuntu
  * windows
  * ubuntu

**Comment by vikman90** [comment]
@mmccarn Thank you for your reply.

As I mentioned, I believe the agent is correctly attempting to refresh the nameserver on each connection attempt. Specifically, it uses the `getaddrinfo()` function from the C standard library, which ultimately delegates the query to the operating system.

I recommend conducting a test by using an alternative method (such as `/etc/hosts`) to determine if the behavior remains the same. With that said, I'll go ahead and close this issue, but feel free to reopen it if you consider it necessary. 

Thank you, and best regards.
