### ISSUE TITLE
Let the agent's CLI output be user friendly

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#245]
Currently, the agent always prints every output in logging format. This is not user friendly for the CLI.

So, we propose:
- Set the standard CLI output as normal text (no logging format) via _stdout_.
- Use _stderr_ for logs.
   - Do not implement this if this causes side effects in the Systemd service.
- Avoid printing logs in the CLI, except, maybe, critical errors.

**Comment by aritosteles** [comment]
# Update

- Logs have been redirected to stderror using `spdlog::sinks::stderr_color_sink_mt` sink. No side effects noticed in Systemd service.
- Output has been changed to plain text in the one case the agent is expected to be run from the CLI (`--register`) and when the agent exits because a previous instance is already running. Every other use case is common to agents being run through the CLI and through systemd, so the Log format was kept.
