### ISSUE TITLE
Design and development of the communicator component for the new agent

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-agent#25]
## Description

As part of the development of the new agent [MVP](https://github.com/wazuh/wazuh-agent/issues/14), it is necessary to develop a new communicator module.

Take into account the following:

- Use the [POC](https://github.com/wazuh/wazuh-agent/issues/1#issuecomment-2163262029) developed as a model to develop this MVP.
- Integrate with the [wazuh-http-request](https://github.com/wazuh/wazuh-http-request) library.
- The module should be able to:
  - Register with the manager. The uuid generation will be done during the registration process.
  - Request a token (authenticate) from the manager.
  - Send `stateless` and `stateful` messages to the manager.
  - Receive `commands` from the manager.
- Use the concurrency control module for task scheduling.

For more considerations (including API endpoints), see the [spike](https://github.com/wazuh/wazuh-agent/issues/1) issue.

**Comment by aritosteles** [comment]
Working branch:
[https://github.com/wazuh/wazuh-agent/tree/enhancement/25-communicator-module-mvp](https://github.com/wazuh/wazuh-agent/tree/enhancement/25-communicator-module-mvp)

**Comment by sdvendramini** [comment]
The branch [test/25-server-mock](https://github.com/wazuh/wazuh-agent/tree/test/25-server-mock) was added to work with communicator module.

**Comment by aritosteles** [comment]
# Update
Project's repository structure and CMakeLists.txt have been modified to allow building the main project and each child project in standalone mode.
After a meeting with @juliancnn where he showed the engine repo structure and the use of CPM to manage dependencies, I have included CPM in Agent project and I am working on modifying wazuh-http-request CMakeLists.txt to remove vcpkg so that all dependencies can be managed by CPM in the main Agent project.

**Comment by sdvendramini** [comment]
# Update
## 07/03/24
I caught up with the progress of the issue and we started to analyze how to reorganize cmakefiles.
## 07/04/24
We continue with the reorganization of the repository structure. I start to modify the PoC server mock to use with the new agent.
