### ISSUE TITLE
MSI Setup bug

### ISSUE THREAD

**Issue by ThomasCr** [wazuh/wazuh-agent#341]
Hi,

today I discovered an strange bug in wazuh-client msi package.

We deploy the MSI via Group Policy with an MST file including the properties for the MSI package.
On systems which are critical and can't rebooted that fast, I manually update the package from command file:

`MSIEXEC /i "\\SRV\share$\folder\CSOC\wazuh-agent-4.9.1-1.msi" TRANSFORMS="\\SRV\share$\folder\CSOC\csoc-sensor.mst" /qb /passive /L*v "%temp%\wazuh-agent-4.9.1-1.log"`

The last version, we used before was 4.7.0-1

Now, I installed the 4.9.1 package manually on two clients. But after a reboot, the policy was kicking in an "checked" or "reinstalled" the package from GPO. This was before never a problem.

But now I found, that on this two clients, the wazuh agent got lost. Okay, I thought I reinstall the package with my command line.... But huu.. Its the same -> The client is not installed. We cant find it on windows uninstall and there are no files in the install folder "C:\Program Files (x86)\ossec-agent\".

Okay, I try to install it manually to check if I get any error message. But the installer completed without any error - and again - no files on the install folder and no uninstall. Also a uninstall on the MSI gives me the error, that the package is not installed.
That was the point I added the logging to my msiexec command, but no - there are also no errors reported.

So I thought I test with the 4.9.2 msi package - But also the same result. I was not able to install wazuh msi package.

Then I tested with the old MSI package 4.7.0 which I had - and voila - I was able to install again. And after that, I updated again with to 4.9.1 with my msiexec command.

This is a really strange behavior and I think it is for sure not normal. Maybe it is a check worth.

The OS is expired the issue was two times Server 2016 Std.

Greetings,
Thomas

I added a logfile from my temp folder, before I used the logfile params. 

[MSIeb442.LOG](https://github.com/user-attachments/files/17870322/MSIeb442.LOG)

**Comment by vikman90** [comment]
Hi @ThomasCr,  

Thank you for reporting this issue and providing detailed information along with the log file.  

We have not encountered this specific behavior before, and while we haven't extensively tested deployments using Group Policy Objects (GPO), your observations are concerning and warrant further investigation. Here's how we can proceed:  

1. **Windows Server Versions**:  
   Could you confirm if this issue is limited to Windows Server 2016, or if it also occurs on other Windows Server versions? This information would help us identify whether the problem is related to the operating system or the MSI package itself.  
2. **Testing Without Transformations**:  
   Have you tried installing the MSI package without applying the transformation file (`csoc-sensor.mst`)? This test would help us determine whether the issue is influenced by the MST file or its specific configurations. You can attempt this using the following command:  
   ```bash
   msiexec /i "\\SRV\share$\folder\CSOC\wazuh-agent-4.9.1-1.msi" /qb /passive /L*v "%temp%\wazuh-agent-test.log"
   ```

Once we have the results of these tests, we’ll be able to better understand the root cause and provide further guidance or fixes as needed.  

We appreciate your patience and collaboration on this matter.

Best regards.

**Comment by dMailonG** [comment]
I'm also having the same issue since 4.7.0.
This single issue is preventing our MSSP from greenlighting the implementation of Wazuh on hundreds of clients.

https://github.com/wazuh/wazuh/issues/20775

**Comment by vikman90** [comment]
@dMailonG Thank you for the additional information and the workaround you provided.

We have conducted several tests in clean environments, including:
- Clean installation of versions 4.9.1 and 4.9.2.
- Updates from 4.9.1 to 4.9.2.
- Clean installation of version 4.7.0.
- Updates from 4.7.0 to 4.7.1 and from 4.7.0 to 4.9.2.

Unfortunately, we have not been able to reproduce the issue you described. This leads us to wonder whether the affected systems had Wazuh Agent previously installed, as there might have been remnants of an incomplete uninstallation. This hypothesis aligns with the behavior you described and the need to clean the Registry to proceed with a clean installation.

On another note, in version 4.10.0, we addressed some installer-related issues, particularly concerning installation folder permissions. However, we do not believe these changes are related to the issue you reported.

To investigate further, we would appreciate it if you could provide the exact steps to reproduce the issue in a clean environment. For instance:
- Details about any specific Registry keys that were left behind.
- The sequence of commands or installation methods used.

With this information, we will attempt to reproduce the issue in our testing environment.

Thank you for your collaboration!

Best regards,

**Comment by jegaprasad** [comment]
Hi All 
We are also facing the same issue upgrade from 4.7 to 4.9.

we push the agent upgrade from console all went good but after sometimes we received multiple agents are disconnect 
upon checking we observed a same alert on disconnected agents ie--

![Image](https://github.com/user-attachments/assets/6e1c864f-a735-429e-9746-efea18517f86)
