### ISSUE TITLE
Wazuh agent unistallation alert

### ISSUE THREAD

**Issue by Malwazu** [wazuh/wazuh-agent#381]
Unable to get alert of wazuh-agent uninstallation. 
If User uninstall wazuh agent then Manger only get status about disconnetion of agent, Manager unable of classify that agent is unistalled or disconnected.
I'm trying to get this alert through event id- 1034 &11724 and increasing level of rule id 505 but it cannot fetch. 
Is anyway to get alert of uninstalled agent by user?

**Comment by vikman90** [comment]
@Malwazu The agent is designed to **capture and send events that occur while it is active**. To capture events that occurred while the agent was stopped, you can use the following configuration option:

```xml
<only-future-events>no</only-future-events>
```
This enables the agent to retrieve and send past events when it starts again.

However, the agent does send an event to indicate it is stopping before it shuts down. This event triggers alert ID 504. Since the agent must be stopped before it can be uninstalled, it cannot report events during its own uninstallation process.

Actions such as installing or uninstalling the agent go beyond the agent's own scope. For these cases, I suggest using an external mechanism to report the uninstallation, such as monitoring system logs or leveraging a third-party tool to track uninstallation events.

Best regards.
