### ISSUE TITLE
Integrate the new client with the Queue component

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-agent#57]
## Description

As part of the development of the new agent [MVP](https://github.com/wazuh/wazuh-agent/issues/14), it is necessary to integrate the new client with the Queue component.

Take into account the following:

- `stateless` and `stateful` requests should get messages to be sent from the Queue.
  - The communicator can specify the type and number of messages to be fetched from the Queue.
- `command` responses should be stored in the Queue.
- The communicator should only handle requests. No need to process messages.

For more considerations, see the [spike](https://github.com/wazuh/wazuh-agent/issues/1) issue.

**Comment by jr0me** [comment]
### Update

Created branch for the story. Some CMake changes were needed to the Queue's CMake files (disable tests, which caused compilation errors, made the include directories public, changed the name of the queue header file since it collided with boost queue for intellisense purposes).

Extended the Communicator class to take two functions, one to get messages and one to push commands.

**Comment by jr0me** [comment]
### Update

Rebased and continue testing with awaitable versions of the queue methods.

**Comment by jr0me** [comment]
### Update

Some issues were addressed: ternary operator used in http_client.cpp:132 was not correctly deducing the type of string when there was no message getter function, resulting in the code hanging on a wrongly deduced awaitable. Re authentication attempts fixed by removing the token timer extension, instead the timer can be cancelled, waking up the coroutine waiting on it.

**Comment by jr0me** [comment]
### Update

Draft PR has been opened. Continuing with testing scenarios.

**Comment by jr0me** [comment]
### Update

Added tests, did some refactoring on the Queue to enable using GMock with it. Addressed comments on the PR's draft.
