### ISSUE TITLE
Adopt vcpkg in the Agent Repository

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-agent#58]
## Description

After [analysis](https://github.com/wazuh/wazuh-agent/issues/38) of suitable tools and systems to manage dependencies in Wazuh, the decision was made to use `vcpkg`. Now, it is necessary to implement and start using `vcpkg` in the new agent repository.

## Tasks

1. **Integrate the tool into the existing build system**:
   - Use `vcpkg` to manage all new agent dependencies, such as `boost`.
   - Create and integrate all configuration files required by `vcpkg`.

2. **Ensure that dependencies can be defined individually and modified independently of the build system**:
   - External dependencies must be independent of each other.
   - Updating a single dependency should not interfere with other dependencies.

3. **Documentation**:
   - Document the steps required to include and manage new external dependencies using `vcpkg`.

## Acceptance Criteria

- A working example of an external dependency in the `vcpkg` repository.
- A documented guide to the steps required to add and update dependencies using `vcpkg`.

## Related Issues

- **Parent:** https://github.com/wazuh/wazuh/issues/16882

**Comment by jr0me** [comment]
## Update

We have been successfully using Vcpkg for the `Wazuh-agent` as seen in: https://github.com/wazuh/wazuh-agent/blob/master/src/CMakeLists.txt#L5 (note that the this vcpkg toolchain needs to be added always before the project function call from CMake).

Vcpkg is a submodule in the repository, so it needs to be initialized with the `git submodule` command, ie: `git submodule update --init --recursive`.

The addition of two files for managing the dependencies was necessary, a manifest json file, and a configuration file.

* Manifest:
  * https://github.com/wazuh/wazuh-agent/blob/master/src/vcpkg.json
* Configuration:
  * https://github.com/wazuh/wazuh-agent/blob/master/src/vcpkg-configuration.json

Vcpkg works with a baseline, which is a certain commit in the vcpkg repository, or as pointed out from their documentation `Baselines define a global version floor for what versions will be considered`. If we want to point out to specific versions we have to add. an override in the manifest file as in https://github.com/wazuh/wazuh-agent/blob/master/src/vcpkg.json#L10-L15:

```json
    "overrides": [
      {
        "name": "toml11",
        "version": "4.0.0"
      }
    ]
```

Together with a registry for the version we want (another baseline in the vcpkg repository where that version is available) https://github.com/wazuh/wazuh-agent/blob/master/src/vcpkg-configuration.json:

```json
    "registries": [
      {
        "kind": "git",
        "repository": "https://github.com/Microsoft/vcpkg",
        "baseline": "42d8e7b4109142b079de1ab7b64e4455c8d02bcc",
        "packages": [ "toml11"]
      }
    ]
```

As noted above, it's necessary to use the Vcpkg cmake toolchain, and it has to be included before the `project` CMake function call in order to work. Subprojects will have to also refer to it in the same manner if they want to use the dependencies from the manifest file, but they will also have to point to it with an additional step:

https://github.com/wazuh/wazuh-agent/blob/master/src/agent/configuration_parser/CMakeLists.txt#L8-L9

```cmake
set(CMAKE_TOOLCHAIN_FILE "${CMAKE_SOURCE_DIR}/../../vcpkg/scripts/buildsystems/vcpkg.cmake")
set(VCPKG_MANIFEST_DIR ${CMAKE_SOURCE_DIR}/../../)
```

Once this is set building normally with CMake and Make will download the dependencies.

For more information, the packages' entries in vcpkg.io usually include information on how to include the dependencies headers in code. But this is also part of the console output when generating the CMake project.

**Comment by ncvicchi** [comment]
Al final solo agregando estas lineas compilo librpm:
include_directories(/home/beto/wazuh/inventory5/wazuh-agent/src/vcpkg/packages/sqlite3_x64-linux/include/)
include_directories(/home/beto/wazuh/inventory5/wazuh-agent/src/vcpkg/packages/libpopt_x64-linux/include/)
include_directories(/home/beto/wazuh/inventory5/wazuh-agent/src/vcpkg/packages/lua_x64-linux/include/)

Pero son fijas. Podrias indicarme como hacerlas relativas tanto a donde se instalo vcpkg como a las variantes que upeda tener vcpkg (me refiero a los postfijos x64 y linux)
