### ISSUE TITLE
Investigate and implement a logger in the new agent

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-agent#92]
## Description

Since the new agent doesn't have a standardized way of logging messages (currently messages are written to `stdout` and `stderr`), it is necessary to research and select a logging tool to accomplish this and implement it throughout the agent code.

Tasks to be accomplished:

- [x] Research different standard logging libraries.
  - [x] Select a library, justify the selection.
- [ ] Implement the library in the new agent code.
  - [ ] The name of the log file should be `wazuh.log`.
  - [ ] Remove uses of `cout` and `cerr`.

**Comment by sdvendramini** [comment]
## 20/08/2024
I've started working on the issue. I was researching existing libraries and strategies for logging in our solution.

**Comment by sdvendramini** [comment]
> [!Note]
> This is a work in progress


After studying different logging strategies, some questions arise that must be defined in order to choose a library. 

By choosing a library I am not discarding the use of syslog (or similar according to OS), but I would choose among the libraries that can change their backend output to have flexibility on this and take advantage of the compatibility of these libraries with different OS. 

It is proposed to develop an interface or wrapper to be able to change vendor in case it is necessary.

To define:

- Levels: the following classification (taken from https://www.dataset.com/blog/the-10-commandments-of-logging/) seems to be more flexible and standardized than the one used in the old agent.
    - TRACE level: this is a code smell if used in production. This should be used during development to track bugs, but never committed to your VCS.
    - DEBUG level: log at this level about anything that happens in the program. This is mostly used during debugging, and I’d advocate trimming down the number of debug statement before entering the production stage, so that only the most meaningful entries are left, and can be activated during troubleshooting.
    - INFO level: log at this level all actions that are user-driven, or system specific (ie regularly scheduled operations…)
    - NOTICE level: this will certainly be the level at which the program will run when in production. Log at this level all the notable events that are not considered an error.
    - WARN level: log at this level all events that could potentially become an error. For instance if one database call took more than a predefined time, or if an in-memory cache is near capacity. This will allow proper automated alerting, and during troubleshooting will allow to better understand how the system was behaving before the failure.
    - ERROR level: log every error condition at this level. That can be API calls that return errors or internal error conditions.
    - FATAL level: too bad, it’s doomsday. Use this very scarcely, this shouldn’t happen a lot in a real program. Usually logging at this level signifies the end of the program. For instance, if a network daemon can’t bind a network socket, log at this level and exit is the only sensible thing to do.

- Categories:
    Many of the libraries allow to sort the logs into categories. To classify the logs, or according to the configuration, directly do not print certain types of logs.
   These categories can be according to the Class and the method where the log is printed.

- Proposed message format
    - Date
    - Level
    - Thread name/id
    - Category (class.method)
    - Message: this can be in an easily parseable format, such as a JSON, containing environment-specific data at the time the log is printed, such as an ID, a timeout, a limit reached, and a brief description.

- Where are the logs stored and when are they rotated?

At this point there are several things to define. 
- The rotation strategy would be configurable? In that case by size and/or by time?
- In case of redirecting the logs to syslog, are they also stored in a file? At this point it may be relevant to investigate and do some proofs of concept with the chosen library.


The following is a table with some of the libraries analyzed and with certain features that are believed to be mandatory.

|                | Log rotation | vcpkg | targets/sinks | categories | async writing | multi platform |
|----------------|--------------|-------|---------------|------------|---------------|----------------|
| **Pantheios**  |              |       |      YES      |            |               |      YES       |
| **Glog**       |              |       |               |            |               |                |
| **log4cpp**    |              |       |               |            |               |                |
| **P7**         |              |       |               |            |               |                |
| **G3log**      |              |       |               |            |               |                |
| **Spdlog**     |              |       |               |            |               |                |
| **Easylogging**|              |       |               |            |               |                |
| **Boost.Log**  |              |       |               |            |               |                |

**Comment by vikman90** [comment]
@sdvendramini Great summary! The format looks excellent. We can later decide on the logging options we want to include.

Regarding the choice of the library, I do have a few things in mind. While it’s important to get support for formatting and some filters, the current proposal suggests outputting logs directly to _stderr_. Then, each platform would handle the redirection to the appropriate storage.

For example, on UNIX-based systems, if the agent runs as a service under Systemd, stderr would be automatically redirected to journald. On Windows, we’ll need to ensure that the logs reach the Event Viewer, as Windows doesn’t handle this automatically. Finally, on macOS, the logs should also end up in the Unified Logging System (ULS). This is what we would expect as the default behavior.

Having the option to redirect logs to a file seems reasonable, and supporting log rotation could be a secondary feature. —Of course, we’ll discuss this further with @gdiazlo—

So, what I would expect from the logging library we choose is:
1. Formatting logs according to our specifications.
2. By default, printing logs to stderr on UNIX, to the Event Viewer on Windows, and to the ULS on macOS.
3. The ability to redirect logs to a file. Initially, I wouldn’t worry too much about log rotation.

**Comment by sdvendramini** [comment]
As in linux, it is possible to configure `spdlog` for windows, by sending the events to the Event Viewer. The code in the agent is practically the same, only the includes must be modified.

```
#include <spdlog/spdlog.h>
#include <spdlog/sinks/win_eventlog_sink.h>
```

In order to define the corresponding object

```
auto win_eventlog_sink = std::make_shared<spdlog::sinks::win_eventlog_sink_st>("Wazuh-Agent");
auto win_event_logger = std::make_shared<spdlog::logger>("wazuh-agent", win_eventlog_sink);
```

The events generated can be seen as follows

![image](https://github.com/user-attachments/assets/18424f00-905d-4b33-90f9-e969c3c61e4a)
![image](https://github.com/user-attachments/assets/b01d7721-0f58-4cf5-bdf6-7ad4b0909000)

**Comment by sdvendramini** [comment]
# Update
## 03/09/2024
I have been working on making the PoC on macOS. I have not been successful compiling the project on this platform. So I will make a new project, very simple in order to test what we need from the library `spdlog`. Surely in the future we will need a dev environment for macOS.

**Comment by sdvendramini** [comment]
Finally we were able to complete the test for macOS, fulfilling the requirements we need for logging in the new agent using the `spdlog` library.

Below you can see some examples with a small PoC very similar to the previous cases. 

Using Console.app

![image](https://github.com/user-attachments/assets/d1856793-16a5-40dd-9f6d-da50b9b9ec90)

Using `log stream`

![image](https://github.com/user-attachments/assets/7a7b48e5-d25e-4e64-88cf-eb52ea8d85c5)

**Comment by sdvendramini** [comment]
The first results are now included using the `Boost.Log` library. A small PoC was performed in macOS. The requirements are met as with `spdlog`. The following results were obtained. 
![image](https://github.com/user-attachments/assets/7ab26958-9dbb-4f06-ba48-5c8439f06527)
![image](https://github.com/user-attachments/assets/86b3ced0-1bf1-40e5-87d1-de5c1112d7f6)

**Comment by sdvendramini** [comment]
Continuing with the `Boost.Log` PoCs, a limitation was found regarding the linux requirements. Within the native sinks or backends of the library to redirect the logs, it is seen that it only supports syslog (https://www.boost.org/doc/libs/1_86_0/libs/log/doc/html/log/detailed/sink_backends.html).

So using this library, it would be necessary to send to journald using `<systemd/sd-journal.h>` and losing the advantages of encapsulating the handling of logs in a single tool for all platforms. 

So we believe that the most convenient thing to do is to use `spdlog`. That besides having the native backend of systemd to send the logs to journald, supports syslog in case in the future this will be necessary.  

CC: @TomasTurina @vikman90 @gdiazlo

**Comment by sdvendramini** [comment]
# Update
## 05/09/2024
I started working on the implementation, the changes will be uploaded to the branch: https://github.com/wazuh/wazuh-agent/tree/enhancement/92-add-logger-in-the-new-agent
